### ISSUE TITLE
cannot delete photo

### ISSUE THREAD

**Issue by rwelty1889** [kartaview/openstreetcam.org#226]
i am trying to clean up a track by deleting some images that are not placed correctly. i am getting the following message: "Photo cannot be deleted! 400 - Bad Request - 690: An unexpected server error has occurred"

the images i am trying to delete are the first few from this track: https://openstreetcam.org/details/1523285/100/track-info

**Comment by joeybab3** [comment]
I can confirm that I receive the same message trying to delete a photo.

**Comment by klg113** [comment]
I think it deletes the image and gives the message because the image is gone and the app is trying to display it still. If I refresh the page the image count goes down for me.

**Comment by SilentSpike** [comment]
Still an issue, looks like the deletion code hits line 238 here (the error message):
https://github.com/openstreetcam/openstreetcam.org/blob/378ca88ceb65b1b2835ce7c1759ddc231b7d99d6/src/app/sequence/sequence-base.component.ts#L212-L239

Here's the `photoService.delete` method being called by that code (which it sounds like is sending a request with an unexpected body - weird because it still works):
https://github.com/openstreetcam/openstreetcam.org/blob/378ca88ceb65b1b2835ce7c1759ddc231b7d99d6/src/app/shared/api-services/osc/photoVx.service.ts#L71-L78

The `_apiService.post` method here:
https://github.com/openstreetcam/openstreetcam.org/blob/378ca88ceb65b1b2835ce7c1759ddc231b7d99d6/src/app/shared/api-services/api-osc.service.ts#L42-L53

**Comment by OttoROSM** [comment]
Any update for this bug, as it is still not possible to delete images.

**Comment by tigren** [comment]
please try delete photos on https://kartaview.org/ now

**Comment by brmonaghan** [comment]
@tigren still not working with upload incomplete tracks
![problem with seq](https://user-images.githubusercontent.com/71337477/124130368-b1c85d00-da4c-11eb-877e-b87dc64dc41e.png)
https://kartaview.org/details/1446818/0/track-info
https://kartaview.org/details/1449274
https://kartaview.org/details/1443154
https://kartaview.org/details/1378810
https://kartaview.org/details/1378321
https://kartaview.org/details/1378281
https://kartaview.org/details/1446418

**Comment by tigren** [comment]
@brmonaghan I can help delete the sequences you mentioned, meanwhile checking the root cause. Sorry for the inconvience

**Comment by brmonaghan** [comment]
Well, Now we have to keep these upload stuck videos? 😞

**Comment by brmonaghan** [comment]
Oh wait. Editing
