### ISSUE TITLE
impossible to select sequences in 360 view mode

### ISSUE THREAD

**Issue by zorglubu** [kartaview/openstreetcam.org#335]
In the map https://kartaview.org/map/, it's usually possible to click on a highlighted way to show pictures sequences at the bottom of the screen. But if I select in the menu "Field of view = 360", it's impossible to grab a sequence. Coming back to "Field of view = All", it's possible, even for 360° sequences.
Thank you to allow selecting a sequence with the 360 view filter.
![image](https://user-images.githubusercontent.com/31647352/124302996-2f31c180-db62-11eb-9287-1ce7bdafb9be.png)

**Comment by zhaitianduo** [comment]
Hey sorry for the late reply, we are looking into this.

**Comment by zhangtiedong0912** [comment]
@zorglubu  hi , we can see the sequence when "field of view = 360", It will be a little slower than if there were no filters at all.you can try again and wait some seconds, if you have any question , please ping me . 
![image](https://user-images.githubusercontent.com/51616101/126023354-857cc209-61b2-44d4-9dbb-fd0cf3d99190.png)

**Comment by zorglubu** [comment]
Here is a link of the area where I am unable to select the sequence of pictures to display them, when I have the filter 360 enabled.
https://kartaview.org/map/@48.777737053598,2.38538066300589,17z
I tested with chromium and Firefox on a Linux Mint system.

To be sure : I can see the blue lines, but I am unable to select one in order to see the pictures.

**Comment by zhangtiedong0912** [comment]
got it , let me check @zorglubu

**Comment by zhangtiedong0912** [comment]
i find the reason, will fixed as soon as possible, thanks for your feedback!!!!

**Comment by zhangtiedong0912** [comment]
@zorglubu  Thanks for your patience, we have found the root cause and will fix it in a few days

**Comment by zhangtiedong0912** [comment]
@zorglubu it works now, please check

**Comment by zorglubu** [comment]
Yes, it's working ! Thank you very much :-)

**Comment by nakic** [comment]
Hmm...I've accessed the link above to check and I don't see anything different: I can see the lines, but when I zoom in, they disappear and I can't see the pictures. If I refresh the page (<Ctrl>-F5) at a high zoom level, the field of view filter resets to "all", but the map remains empty of photos or traces. What gives?

**Comment by zorglubu** [comment]
That's true. It's working for some tracks, and not working for some others...

**Comment by miruna-craciun** [comment]
@zhangtiedong0912 - can you look into it?

**Comment by zhangtiedong0912** [comment]
Yes, I will check

> 2021年8月8日 下午2:20，zorglubu ***@***.***> 写道：
> 
> That's true. It's working for some tracks, and not working for some others...
> 
> 


-- 


By communicating with Grab Inc and/or its subsidiaries, associate 
companies and jointly controlled entities (“Grab Group”), you are deemed to 
have consented to the processing of your personal data as set out in the 
Privacy Notice which can be viewed at https://grab.com/privacy/ 
<https://grab.com/privacy/>


This email contains confidential information 
and is only for the intended recipient(s). If you are not the intended 
recipient(s), please do not disseminate, distribute or copy this email 
Please notify Grab Group immediately if you have received this by mistake 
and delete this email from your system. Email transmission cannot be 
guaranteed to be secure or error-free as any information therein could be 
intercepted, corrupted, lost, destroyed, delayed or incomplete, or contain 
viruses. Grab Group do not accept liability for any errors or omissions in 
the contents of this email arises as a result of email transmission. All 
intellectual property rights in this email and attachments therein shall 
remain vested in Grab Group, unless otherwise provided by law.

**Comment by zhangtiedong0912** [comment]
@zorglubu  Can you give me a link? , i will check it.

**Comment by zorglubu** [comment]
I am far from any computer for one more week, try the link above, or please wait for few days 😊

10 août 2021 03:28:38 tiedong.zhang ***@***.***>:

**Comment by zorglubu** [comment]
Hello, you can try here : https://kartaview.org/map/@48.777603967397596,2.3850497652485956,17z

When I click on the right side of the screen, on Avenue Lemerle Vetter, I am unable to select the track.
But it's working on the left side of the screen, on Voie Georges Carré.
